### ISSUE TITLE
please update

### ISSUE THREAD

**Issue by e-zk** [spartan117au/basic-tmux#1]
i tried to install from my windows pc and it is not working please help

**Comment by spartan117au** [comment]
I'd just like to interject for a moment. What you're referring to as open source software, is in fact, free/open source software, or as I've recently taken to calling it, free and open source software. Open source software is not software freedom unto itself, but rather another essential component of a fully free program made useful by the freedom to run the program as you wish for any purpose, the freedom to redistribute copies and the freedom to distribute copies of your modified versions to others, comprising a fully free program as defined by the FSF.

Many computer users run free software every day, without realizing it. Through a peculiar turn of events, the licenses that are widely used today are often called open source, and many of its users are not aware that it is basically free software, defined by the GNU Project.

There really is open source software, and these people are using it, but it is just a part of the programs they use. Open source means access to source code: the freedom to study how the program works, and change it so it does your computing as you wish. Access to source code is an essential part of free software, but useless by itself; it can only function in the context of a completely free program. Open source software is normally used in combination with a free software license: the whole program is basically free software. All the so-called open source programs are really free software!
